version: '3.8'

services:
  db:
    image: postgres:14.9-alpine3.18
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=movies_database
      - POSTGRES_PASSWORD=123qwe
    ports:
      - 127.0.0.1:5430:5432
    volumes:
      - ../postgres_init/movies_database.ddl:/docker-entrypoint-initdb.d/movies_db.sql
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  api:
    build: ../../movies_admin
    container_name: api
    restart: always
    depends_on:
      - db
    environment:
      - DB_NAME=movies_database
      - DB_HOST=db
      - DB_USER=app
      - DB_PASSWORD=123qwe
      - DB_PORT=5432
      - DEBUG=True
      - SECRET_KEY=ll
      - UWSGI_PROCESSES 1
      - UWSGI_THREADS 16
      - UWSGI_HARAKIRI 240
    volumes:
      - static_value:/opt/app/django_static/ 
      - media_value:/opt/app/django_media/ 
    expose:
      - 8000
  nginx: 
    image: nginx:1.19.3 
    ports: 
      - 80:80
    expose:
      - 80
    restart: always 
    volumes: 
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/site.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/django_static/  
      - media_value:/var/html/django_media/ 
    depends_on: 
      - api

volumes: 
  static_value: 
  media_value: 
  postgres_data: 